
name: Deploy Nightly
on:
  # This can be used to automatically publish nightlies at UTC nighttime
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
  # This can be used to allow manually triggering nightlies from the web interface
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  wled_build:
    uses: ./.github/workflows/build.yml
  nightly:
    name: Deploy nightly
    runs-on: ubuntu-latest
    needs: wled_build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - name: Show Files
        run: ls -la
      - name: "✏️ Generate release changelog"
        id: changelog
        uses: janheinrichmerker/action-github-changelog-generator@v2.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 
          sinceTag: v16.0.0
          output: CHANGELOG_NIGHTLY.md
          # Exclude issues that were closed without resolution from changelog
          excludeLabels: 'stale,wontfix,duplicate,invalid,external,question,use-as-is,not_planned'
      - name: Update Nightly Release
        uses: andelf/nightly-release@5834076edc55cc05975561c9722043f072ac5c26
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          name: 'Development Nightly (unstable) Build $$'
          prerelease: true
          body_path: CHANGELOG_NIGHTLY.md
          files: |
            *.bin
            *.bin.gz
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: wled/WLED-WebInstaller
          event-type: release-nightly
          token: ${{ secrets.PAT_PUBLIC }}
