# bundle exec jekyll serve --host=0.0.0.0

title: Asynchronous HTTP and WebSocket Server Library for ESP32
description: "Supports: WebSocket, SSE, Authentication, Arduino Json 7, File Upload, Static File serving, URL Rewrite, URL Redirect, etc"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  