#define SS_PIN 			18
#define MOSI_PIN 		27
#define MISO_PIN		19
#define SCK_PIN     	5
#define LORA_RST_PIN 	0
#define DIO0_PIN        26
#define LED_PIN         25
#define RST_OLED_PIN    16
#define SCL_OLED_PIN    15
#define SDA_OLED_PIN    4
#define TXD2_PIN        17
#define RXD2_PIN        34