#define SS_PIN 			15
#define MOSI_PIN 		13
#define MISO_PIN		23
#define SCK_PIN     	14
#define LORA_RST_PIN 	27
#define DIO0_PIN        26
#define LED_PIN         25
#define RST_OLED_PIN    16
#define SCL_OLED_PIN    15
#define SDA_OLED_PIN    4
#define TXD2_PIN        17
#define RXD2_PIN        34
#define BUTTON          2