#include "tests/fl/gfx/canvas.hpp"
#include "tests/fl/gfx/draw_line.hpp"
#include "tests/fl/gfx/draw_disc.hpp"
#include "tests/fl/gfx/draw_disc_16.hpp"
#include "tests/fl/gfx/draw_ring.hpp"
#include "tests/fl/gfx/draw_thick_line.hpp"
#include "tests/fl/gfx/perf_primitives.hpp"
